--
CREATE TABLE IF NOT EXISTS SC_Cat 
(
	SC_Cat_id INT NOT NULL AUTO_INCREMENT,
	Category VARCHAR(20) NOT NULL UNIQUE,
	PRIMARY KEY (SC_Cat_id)
);
---
CREATE TABLE IF NOT EXISTS SC_Char 
(
	SC_Char_id INT NOT NULL AUTO_INCREMENT,
	Characteristic VARCHAR(20) NOT NULL UNIQUE,
	Value VARCHAR(10) DEFAULT 'Ratio',
	DataType VARCHAR(10) DEFAULT 'Char',
	SC_Cat_id INT NOT NULL,
	Status CHAR(1) NOT NULL,
	PRIMARY KEY (SC_Char_id),
	FOREIGN KEY (SC_Cat_id) REFERENCES SC_Cat(SC_Cat_id)
);
--
CREATE TABLE IF NOT EXISTS SC_Conf
(
	SC_Conf_id INT(11) NOT NULL AUTO_INCREMENT,
	Product_id INT NOT NULL UNIQUE,
	SC_Cat_id INT NOT NULL,
	SC_Char_id INT NOT NULL,
	Green VARCHAR(20) NOT NULL,
	Amber VARCHAR(20) NOT NULL,
	Red VARCHAR(20) NOT NULL,
	PRIMARY KEY (SC_Conf_id),
	FOREIGN KEY (SC_Cat_id) REFERENCES SC_Cat(SC_Cat_id),
	FOREIGN KEY (SC_Char_id) REFERENCES SC_Char(SC_Char_id)
);
---
CREATE TABLE IF NOT EXISTS SC_Char_Crit
(
	SC_Char_Crit_id INT(11) NOT NULL AUTO_INCREMENT,
	SC_Char_id INT(11) NOT NULL,
	Datasource VARCHAR(10) NOT NULL,
	Request VARCHAR(10) NOT NULL,
	CallMethod VARCHAR(100) NOT NULL,
	Statistical CHAR(1) NOT NULL,
	PRIMARY KEY (SC_Char_Crit_id),
	FOREIGN KEY (SC_Char_id) REFERENCES SC_Char(SC_Char_id)
);
--
CREATE TABLE IF NOT EXISTS SC_Char_Crit_Value
(
	SC_Char_Crit_Value_id INT(11) NOT NULL AUTO_INCREMENT,
	SC_Char_Crit_id INT NOT NULL,
	Criteria VARCHAR(20) NOT NULL,
	Value VARCHAR(20) NOT NULL,
	PRIMARY KEY (SC_Char_Crit_Value_id),
	FOREIGN KEY (SC_Char_Crit_id) REFERENCES SC_Char_Crit(SC_Char_Crit_id)
);
--
CREATE TABLE IF NOT EXISTS Scorecard
(
	Scorecard_id INT(11) NOT NULL AUTO_INCREMENT,
	Loan_id INT(11) NOT NULL,
	Model VARCHAR(20) NOT NULL,
	Saved_Model_Data JSON,
	PRIMARY KEY (Scorecard_id)
);